version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cutme-app
    ports:
      - "8080:8080" # Mapeia a porta 8080 do container para o host
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"
        max-file: "3"
