// Code generated by MockGen. DO NOT EDIT.
// Source: CutMe/internal/application/repository (interfaces: PresignedURLGenerator)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockPresignedURLGenerator is a mock of PresignedURLGenerator interface.
type MockPresignedURLGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockPresignedURLGeneratorMockRecorder
}

// MockPresignedURLGeneratorMockRecorder is the mock recorder for MockPresignedURLGenerator.
type MockPresignedURLGeneratorMockRecorder struct {
	mock *MockPresignedURLGenerator
}

// NewMockPresignedURLGenerator creates a new mock instance.
func NewMockPresignedURLGenerator(ctrl *gomock.Controller) *MockPresignedURLGenerator {
	mock := &MockPresignedURLGenerator{ctrl: ctrl}
	mock.recorder = &MockPresignedURLGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPresignedURLGenerator) EXPECT() *MockPresignedURLGeneratorMockRecorder {
	return m.recorder
}

// GeneratePreSignedURL mocks base method.
func (m *MockPresignedURLGenerator) GeneratePreSignedURL(arg0, arg1, arg2 string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePreSignedURL", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GeneratePreSignedURL indicates an expected call of GeneratePreSignedURL.
func (mr *MockPresignedURLGeneratorMockRecorder) GeneratePreSignedURL(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePreSignedURL", reflect.TypeOf((*MockPresignedURLGenerator)(nil).GeneratePreSignedURL), arg0, arg1, arg2)
}

// GetBucketName mocks base method.
func (m *MockPresignedURLGenerator) GetBucketName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBucketName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBucketName indicates an expected call of GetBucketName.
func (mr *MockPresignedURLGeneratorMockRecorder) GetBucketName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBucketName", reflect.TypeOf((*MockPresignedURLGenerator)(nil).GetBucketName))
}

// GetURLValidity mocks base method.
func (m *MockPresignedURLGenerator) GetURLValidity() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLValidity")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetURLValidity indicates an expected call of GetURLValidity.
func (mr *MockPresignedURLGeneratorMockRecorder) GetURLValidity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLValidity", reflect.TypeOf((*MockPresignedURLGenerator)(nil).GetURLValidity))
}
